version: '3'
services:
  portainer:
    image: portainer/portainer
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    ports:
        - "9000:9000"
    container_name: portainer
  mariadb:
    image: mariadb
    container_name: mariadb
    restart: always
    ports:
      # just if you also want to access it directly from you host
      # node neede for phpmyadmin
      - "3306:3306" 
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: wordpress   
  phpmyadmin:
    image: jackgruber/phpmyadmin:5.0.2-armhf
    container_name: phpmyadmin
    ports:
      - "9090:80"
    depends_on:
      - mariadb
    environment: 
        PMA_HOSTS: mariadb  
        # PMA_PORT: 3306 
        #  MYSQL_ROOT_PASSWORD: admin       
  wordpress:
    image: wordpress
    container_name: wordpress
    restart: always
    ports:
      - "80:80"
    links:
      - mariadb
    depends_on:
      - mariadb
      # network_mode: "bridge"
      # links:
      #   - "mariadb"
    environment: 
        WORDPRESS_DB_PASSWORD: admin       
        WORDPRESS_DB_HOST: mariadb
        WORDPRESS_DB_NAME: wordpress