version: '3'
services:
  portainer:
    image: portainer/portainer
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    ports:
        - "9000:9000"
    container_name: portainer
  mariadb:
    image: mariadb
    container_name: mariadb
    restart: always
    ports:
      # just if you also want to access it directly from you host
      # node neede for phpmyadmin
      - "3306:3306" 
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: wordpress   
  phpmyadmin:
    image: jackgruber/phpmyadmin:5.0.2-armhf
    container_name: phpmyadmin
    restart: always
    ports:
      - "9090:80"
    depends_on:
      - mariadb
    environment: 
        PMA_HOSTS: mariadb  
        # PMA_PORT: 3306 
        #  MYSQL_ROOT_PASSWORD: admin       
  wordpress:
    image: wordpress
    container_name: wordpress
    restart: always
    ports:
      - "80:80"
    links:
      - mariadb
    depends_on:
      - mariadb
      # network_mode: "bridge"
      # links:
      #   - "mariadb"
    environment: 
        WORDPRESS_DB_PASSWORD: admin       
        WORDPRESS_DB_HOST: mariadb
        WORDPRESS_DB_NAME: wordpress
  ros:
    image: ros
    container_name: ros
    restart: always
    #sudo docker run -it --net=host --name=ros -e DISPLAY -v /tmp/.x11-unix ros bash
    # you have to do "apt=get install xauth" inside the ros container 
  jupyter:
    image: johntrimble/jupyter-multiarch:lates
    container_name: jupyter
    restart: always
    ports:
      - "8888:8888"
    #After this is dun you need to logininto the juputer docker container and run the command " jupyter notebook password" to setup the password.
  jenkins:
    image: jenkins4eval/jenkins
    container_name: jenkins
    restart: always
    ports:
      - "8085:8080"
  kali-linux:
    image: donaldrich/kali-linux
    container_name: kali-linux
    working_dir: /root